name: Release
on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags like v1.0.0, v2.1.3, etc.

jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write  # Required to create releases and upload assets
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: 2.8.2
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # Use a personal access token for authentication